/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./components/Avatar/AvatarMenu.vue')['default']
    ChangeLocale: typeof import('./components/Themes/ChangeLocale.vue')['default']
    CollapseTransition: typeof import('./components/Transition/CollapseTransition.vue')['default']
    DarkModeToggle: typeof import('./components/Themes/DarkModeToggle.vue')['default']
    DragIcon: typeof import('./components/Table/DragIcon.vue')['default']
    Dropdown: typeof import('./components/Menu/Dropdown.vue')['default']
    Editor: typeof import('./components/Editor/Editor.vue')['default']
    FormLayout: typeof import('./components/Form/FormLayout.vue')['default']
    FullScreen: typeof import('./components/Themes/FullScreen.vue')['default']
    Header: typeof import('./components/Layouts/Header.vue')['default']
    HeaderTabs: typeof import('./components/Layouts/HeaderTabs.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Iconify: typeof import('./components/Icon/Iconify.vue')['default']
    IconList: typeof import('./components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./components/Icon/IconPicker.vue')['default']
    LoginForm: typeof import('./components/Form/LoginForm.vue')['default']
    Menu: typeof import('./components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./components/Menu/MenuItem.vue')['default']
    Notice: typeof import('./components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./components/Notice/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./components/Menu/SubMenu.vue')['default']
    SvgIcon: typeof import('./components/Icon/SvgIcon.vue')['default']
    ThemeSettings: typeof import('./components/Themes/ThemeSettings.vue')['default']
    VBreadcrumb: typeof import('./components/Themes/VBreadcrumb.vue')['default']
    VECharts: typeof import('./components/Chart/VECharts.vue')['default']
    VForm: typeof import('./components/Form/VForm.vue')['default']
    VFormItem: typeof import('./components/Form/VFormItem.vue')['default']
    VFormLayoutSchema: typeof import('./components/Form/VFormLayoutSchema.vue')['default']
    VTable: typeof import('./components/Table/VTable.vue')['default']
    VTableColumn: typeof import('./components/Table/VTableColumn.vue')['default']
  }
}
