/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./components/Avatar/AvatarMenu.vue')['default']
    ChangeLocale: typeof import('./components/Themes/ChangeLocale.vue')['default']
    DarkModeToggle: typeof import('./components/Themes/DarkModeToggle.vue')['default']
    Dropdown: typeof import('./components/Menu/Dropdown.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FullScreen: typeof import('./components/Themes/FullScreen.vue')['default']
    Header: typeof import('./components/Layouts/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Iconify: typeof import('./components/Icon/Iconify.vue')['default']
    IconList: typeof import('./components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./components/Icon/IconPicker.vue')['default']
    Menu: typeof import('./components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./components/Menu/MenuItem.vue')['default']
    Notice: typeof import('./components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./components/Notice/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./components/Menu/SubMenu.vue')['default']
    SvgIcon: typeof import('./components/Icon/SvgIcon.vue')['default']
    ThemeSettings: typeof import('./components/Themes/ThemeSettings.vue')['default']
  }
}
